export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const CONSTRUCTED_LIST_OF_SPARQL = "CONSTRUCTED_LIST_OF_SPARQL";
export const CONSTRUCTED_ITEM_CODE_SPARQL = "CONSTRUCTED_LIST_OF_SPARQL";
export const ITEM_CODE_LOADED = 'ITEM_CODE_LOADED';
